name:       pushme
version:    2.1.2
synopsis:   Tool to synchronize directories with rsync, zfs or git-annex
github:     jwiegley/pushme
author:     John Wiegley
maintainer: johnw@newartisans.com
category:   System
license:    BSD3

description:
  Script I use for synchronizing data among machines.

dependencies:
  - base                 >= 4.7  && < 5.0
  - aeson
  - bytestring           >= 0.10 && < 0.11
  - pipes
  - pipes-group
  - pipes-safe
  - pipes-text
  - foldl
  - containers           >= 0.5  && < 0.6
  - io-storage           >= 0.3  && < 0.4
  - lens                 >= 4.9  && < 5.0
  - logging              >= 3.0  && < 3.1
  - monad-logger         >= 0.3  && < 0.4
  - old-locale           >= 1.0  && < 1.1
  - optparse-applicative >= 0.10 && < 1.0
  - parallel-io          >= 0.3  && < 0.4
  - regex-posix          >= 0.95 && < 1.0
  - safe                 >= 0.3  && < 0.4
  - shelly               >= 1.6  && < 2.0
  - system-fileio        >= 0.3  && < 0.4
  - system-filepath      >= 0.4  && < 0.5
  - temporary            >= 1.2  && < 2.0
  - text                 >= 1.2  && < 1.3
  - text-format          >= 0.3  && < 0.4
  - time                 >= 1.4  && < 2.0
  - transformers         >= 0.3  && < 0.6
  - unix                 >= 2.6  && < 2.8
  - unordered-containers >= 0.2  && < 0.3
  - yaml

extra-source-files:
  - README.md

executables:
  pushme:
    main: Main.hs
    ghc-options: -threaded
    other-modules:
      - Pushme.Options
