name:       pushme
version:    2.2.0
synopsis:   Tool to synchronize directories with rsync, zfs or git-annex
github:     jwiegley/pushme
author:     John Wiegley
maintainer: johnw@newartisans.com
category:   System
license:    BSD3

description:
  Script I use for synchronizing data among machines.

dependencies:
  - base                 >= 4.7
  - aeson
  - bytestring           >= 0.10
  - containers           >= 0.6
  - directory
  - filepath
  - foldl
  - io-storage           >= 0.3
  - lens                 >= 4.9
  - logging              >= 3.0.6
  - monad-logger         >= 0.3
  - old-locale           >= 1.0
  - optparse-applicative >= 0.10
  - parallel-io          >= 0.3
  - regex-posix          >= 0.95
  - safe                 >= 0.3
  - shelly               >= 1.6
  - system-fileio        >= 0.3
  - system-filepath      >= 0.4
  - temporary            >= 1.2
  - text                 >= 1.2
  - time                 >= 1.4
  - transformers         >= 0.3
  - unix                 >= 2.6
  - unordered-containers >= 0.2
  - yaml

extra-source-files:
  - README.md

executables:
  pushme:
    main: Main.hs
    ghc-options: -threaded
    other-modules:
      - Pushme.Options
