name:       pushme
version:    3.0.0
synopsis:   Synchronize multiple filesets across machines using rsync
github:     jwiegley/pushme
author:     John Wiegley
maintainer: johnw@newartisans.com
category:   System
license:    BSD3

description:
  pushme is a wrapper around rsync allowing declarative filesets to be
  transferred between machines. The screenshot above shows pushme in action
  (where `push` is a script I use to call `pushme` with appropriate arguments
  based on which machine I'm running it from).

ghc-options:
  - -Wall
  - -Wno-missing-home-modules

dependencies:
  - base                 >= 4.7    && < 4.21
  - aeson                >= 1.0    && < 2.3
  - bytestring           >= 0.10   && < 0.13
  - containers           >= 0.6    && < 0.8
  - directory            >= 1.2    && < 1.4
  - filepath             >= 1.4    && < 1.6
  - foldl                >= 1.4    && < 1.5
  - lens                 >= 4.9    && < 5.4
  - logging              >= 3.0.6  && < 3.1
  - monad-logger         >= 0.3    && < 0.4
  - old-locale           >= 1.0    && < 1.1
  - optparse-applicative >= 0.10   && < 0.19
  - parallel-io          >= 0.3    && < 0.4
  - pretty-show          >= 1.10   && < 1.11
  - process              >= 1.6    && < 1.7
  - regex-posix          >= 0.95   && < 0.97
  - system-fileio        >= 0.3    && < 0.4
  - system-filepath      >= 0.4    && < 0.5
  - temporary            >= 1.2    && < 1.4
  - text                 >= 1.2    && < 2.2
  - time                 >= 1.4    && < 1.15
  - transformers         >= 0.3    && < 0.7
  - unix                 >= 2.6    && < 2.9
  - unordered-containers >= 0.2    && < 0.3
  - yaml                 >= 0.11   && < 0.12

extra-source-files:
  - README.md

executables:
  pushme:
    main: Main.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    other-modules:
      - Pushme.Options
