Name:     'Applications'
Priority: 95
Class:    'system,main,sync'

Stores:
  vulcan:
    Rsync:
      ReceiveFrom:
        - hermes
      Path: /Applications/Misc
  
  mybook:
    Path: /Volumes/mybook/Applications

  tank:
    Path: /Volumes/tank/Applications

  hermes:
    Rsync:
      ReceiveFrom:
        - vulcan
      Path: /Applications/Misc
  
  titan:
    Rsync:
      ReceiveFrom:
        - tank
      Path: /tank/Applications
